<a href="https://colab.research.google.com/github/Benjamin1118/Shark_Tank/blob/main/Shark_tank.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# import some basic libraries to start
import csv
import pandas as pd
import numpy as np
import re

#import nltk

# upload data into system using pd.read_csv
df = pd.read_csv('/content/shark_tank.csv')
# find shape
print(df.shape)
# print head of df
df.head()


(495, 19)


deal  ... Multiple Entreprenuers
0  False  ...                  False
1   True  ...                  False
2   True  ...                  False
3  False  ...                  False
4  False  ...                  False

[5 rows x 19 columns]

In [2]:
# for this project I don't need episode, location, episode-season, website or season
df = df.drop(['episode', 'location', 'episode-season', 'website','season', 'shark1', 'shark2', 'shark3', 'shark4', 'shark5',"Multiple Entreprenuers"], axis = 1)
# print changes to shape and verify they are true with printing head of df
print(df.shape)
df.head()

(495, 8)


deal  ...                        title
0  False  ...                    Ionic Ear
1   True  ...        Mr. Tod's Pie Factory
2   True  ...             Ava the Elephant
3  False  ...  College Foxes Packing Boxes
4  False  ...                      Wispots

[5 rows x 8 columns]

In [3]:
# turning the true and false of deal to 1 or 0
df['deal'] = df['deal'].astype(int)

#making sure it did it correctly
df.head()

deal  ...                        title
0     0  ...                    Ionic Ear
1     1  ...        Mr. Tod's Pie Factory
2     1  ...             Ava the Elephant
3     0  ...  College Foxes Packing Boxes
4     0  ...                      Wispots

[5 rows x 8 columns]

In [4]:
def data_cleaning(corpus):
  letters_only = re.sub('[^a-zA-Z]', " ", corpus)
  words = letters_only.lower().split()
  return( ' '.join( words ))

In [5]:
df['description'] = df['description'].apply(lambda x: data_cleaning(x))
df['description']

0                  bluetooth device implant for your ear
1      retail and wholesale pie factory with two reta...
2      ava the elephant is a godsend for frazzled par...
3      organizing packing and moving services deliver...
4      interactive media centers for healthcare waiti...
                             ...                        
490    zoom interiors is a virtual service for interi...
491    spikeball started out as a casual outdoors gam...
492    shark wheel is out to literally reinvent the w...
493    adriana montano wants to open the first cat ca...
494    sway motorsports makes a three wheeled all ele...
Name: description, Length: 495, dtype: object

In [6]:
# split data into train and test
from sklearn.model_selection import train_test_split
train, test = train_test_split(df, test_size = .20)


In [7]:
# Vectorize
train_corpus = []
test_corpus = []
for i in train["description"]:
  train_corpus.append(i)
for i in test["description"]:
  test_corpus.append(i)

# create
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer(ngram_range=(2,2))
train_features = v.fit_transform(train_corpus)
test_features = v.transform(test_corpus)

In [8]:
print(train_features.shape)
print(test_features.shape)

(396, 11169)
(99, 11169)


In [31]:
# Import ML models from sklearn
from sklearn.linear_model import LogisticRegression # Regression classifier
from sklearn.tree import DecisionTreeClassifier # decision tree classifier
from sklearn import svm # support vector machine
from sklearn.ensemble import RandomForestClassifier
#!pip install XGBoost  as XGB # RF and GBC
from sklearn.naive_bayes import MultinomialNB # naive bayes classifier
from sklearn.metrics import accuracy_score, recall_score, confusion_matrix # metrics to check performance of modelfrom sklearn.model_selection import train_test_split



In [10]:
# set params for algorithms 
Classifiers = {'LR': LogisticRegression(random_state=42, C = 5, max_iter=200),
             'DTC': DecisionTreeClassifier(random_state=42, min_samples_leaf=2),
             'RF': RandomForestClassifier(random_state= 42, n_estimators= 100,n_jobs=-1),
             #'XGB': XGB(random_state = 42, n_estimators = 400, learning_rate = .2),
             "SVM": svm.SVC(kernel="linear", C = .1),
             'NB': MultinomialNB(alpha=.05)}

In [11]:
# create pipeline
def ML_Pipeline(clf_name):
  clf = Classifiers[clf_name]
  fit = clf.fit(train_features, train["deal"])
  pred = clf.predict(test_features)
  Accuracy = accuracy_score(test['deal'],pred)
  Confusion_matrix = confusion_matrix(test['deal'], pred)
  
  print("Accuracy = "+ str(Accuracy))
  
  print(Confusion_matrix)

Run the  test through a few different classification systems and see their results.

In [30]:
ML_Pipeline('LR')

Accuracy = 0.5454545454545454
[[36 10]
 [35 18]]


In [25]:
ML_Pipeline('DTC')

Accuracy = 0.5555555555555556
[[41  5]
 [39 14]]


In [26]:
ML_Pipeline('RF')

Accuracy = 0.5252525252525253
[[45  1]
 [46  7]]


In [27]:
ML_Pipeline('SVM')

Accuracy = 0.5555555555555556
[[38  8]
 [36 17]]


In [28]:
ML_Pipeline('NB')

Accuracy = 0.5959595959595959
[[27 19]
 [21 32]]
